Add log reader
ffc-nectec/airsync pull request #10
Opened 2018-08-10 08:11 UTC by lionants02

แก้ข้อมูลบ้าน บนฐาน JHCISDB บน Cloud จะแก้ตามด้วย

2018-08-10 08:32 UTC, porntipa commented
Test Result 
ทดสอบโดยแก้ไขบ้านเลขที่ ที่ฐาน J แล้ว GET ที่ Postman ข้อมูลอัพเดท
      - บ้านเลขที่

      -   Location  > Pass

      -   Timestamp ต้องตรงกับ update date ของ JHCIS > fail

       - fail : timestamp ต้องตรงกับ update date ของ JHCIS

2018-08-11 04:26 UTC, piruin requested changes
refactor LogReaderV1 และ V2 ให้ชัดเจนว่า class ไหนทำอะไรให้ชัดเจน อาจจะแบบเป็นหลาย class เพื่อทำเฉพาะส่วน หรือรวมเป็น clsss เดียว

2018-08-11 04:26 UTC, piruin commented on airsync/src/main/kotlin/ffc/airsync/api/UploadSpliter.kt
> +            // Thread.sleep(1000)
โค้ดไม่ใช้แล้วเอาออกไปเลย ไม่ต้อง comment เก็บไว้

2018-08-11 04:26 UTC, piruin commented on impl/airsync-jhcis-db/src/main/kotlin/ffc/airsync/db/QueryHouse.kt
> +	house.dateupdate
จัด format sql ให้อ่านง่าย

2018-08-11 04:26 UTC, piruin commented on impl/airsync-jhcis-db/src/main/kotlin/ffc/airsync/db/QueryHouse.kt
> +    fun get(@Define("where") whereString: String): List<House>
rename findThat()

2018-08-11 04:26 UTC, piruin commented on impl/airsync-local-web/src/main/java/ffc/airsync/localweb/Dummy.kt
> +class Dummy
มีการเรียกใช้รึเปล่า ถ้าไม่มีลบออกเลย

2018-08-11 04:26 UTC, piruin commented on impl/airsync-local-web/src/main/java/ffc/airsync/localweb/webresources/IndexResource.kt
> +        } catch (ex: Exception) {
try กับ catch block น่าจะไม่จำเป็นแล้ว

2018-08-14 09:50 UTC, piruin requested changes
ดีมากครับ เปลี่ยนชื่อแล้วเค้าใจง่ายขึ้นเยอะ  เพิ่มเติมอีกหน่อยคือ 
1. ให้ LogReader รับ ReadTextFile เป็น Parameter จะได้ลดการส่งต่อ param อย่าง filepath และ delay  และสามารถปรับ realtime ได้จาก  class ด้านนอก 
2. ReadTextFile เปลี่ยนเป็น TextFileReader เพื่อเป็น Pattern เดียวกับ LogReader 
3. ReadTextFile Convert เป็น kt เลย
4. DebugTest ไม่มีการ assert ใน LogReaderV2() และ LogReaderV1() ลองคิดดูว่าจะ assest อะไรได้บ้างเพื่อช่วยให้มั่นใจว่า code ยังทำงานได้ และไม่มี @Test ถ้ารัน เป็น unit ไม่ได้ให้ใส่ @ignore พร้อมเหตุผล ปล. อย่าลืม rename

2018-08-14 09:50 UTC, piruin commented on impl/airsync-mysql-log-reader/src/test/java/th/in/ffc/airsync/logreader/DebugTest.kt
>                                                            String, keyWhere: String ->
บรรทดเดียวไปเลย ไม่ต้องใส่ type

2018-08-14 09:50 UTC, piruin commented on impl/airsync-mysql-log-reader/src/test/java/th/in/ffc/airsync/logreader/DebugTest.kt
>  class DebugTest {
Test อะไร ใส่ชื่อ Class ให้ชัดเจน

2018-08-14 09:50 UTC, piruin commented on impl/airsync-mysql-log-reader/src/test/java/th/in/ffc/airsync/logreader/LogReaderTest.kt
>                  onLogInput = { tableName,
ระวังการขึ้นบรรทัดใหม่ที่ไม่จำเป็น

2018-08-16 05:36 UTC, piruin approved these changes
ปรับแก้ได้ไม่ตกหล่นเลย สุดยอด
Class HowToUse สร้างสรรค์ดีนะชอบ

2018-08-16 08:17 UTC, merged